[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"
